var searchData=
[
  ['files',['files',['../structfiles.html',1,'']]],
  ['findtransform',['FindTransform',['../structflex_prox_dual_l2_inf_1_1_find_transform.html',1,'flexProxDualL2Inf']]],
  ['flexbox',['flexBox',['../classflex_box.html',1,'flexBox&lt; T &gt;'],['../classflex_box.html#aa325ce1968dc664c0e8e37bdefc25247',1,'flexBox::flexBox()']]],
  ['flexboxdata',['flexBoxData',['../classflex_box_data.html',1,'']]],
  ['flexboxdatacpu',['flexBoxDataCPU',['../classflex_box_data_c_p_u.html',1,'']]],
  ['flexboxdatagpu',['flexBoxDataGPU',['../classflex_box_data_g_p_u.html',1,'']]],
  ['flexconcatoperator',['flexConcatOperator',['../classflex_concat_operator.html',1,'flexConcatOperator&lt; T &gt;'],['../classflex_concat_operator.html#aa0b80af6e02e39f68c5d2a07f5e7503d',1,'flexConcatOperator::flexConcatOperator()']]],
  ['flexdiagonaloperator',['flexDiagonalOperator',['../classflex_diagonal_operator.html',1,'flexDiagonalOperator&lt; T &gt;'],['../classflex_diagonal_operator.html#affc1bfd1944ccf07c179ae3d4855f7af',1,'flexDiagonalOperator::flexDiagonalOperator(std::vector&lt; T &gt; aDiagonalElements, bool aMinus)'],['../classflex_diagonal_operator.html#a9e39335b75df3ac690aa3899f4a1a5e4',1,'flexDiagonalOperator::flexDiagonalOperator(Tdata aDiagonalElements, bool aMinus)']]],
  ['flexfullmatrix',['flexFullMatrix',['../classflex_full_matrix.html',1,'flexFullMatrix&lt; T &gt;'],['../classflex_full_matrix.html#a125feeded467ace162fc6b1002df6ef2',1,'flexFullMatrix::flexFullMatrix()'],['../classflex_full_matrix.html#a1523d991180fa00de2db44b10231987b',1,'flexFullMatrix::flexFullMatrix(int aNumRows, int aNumCols, bool aMinus)']]],
  ['flexgradientoperator',['flexGradientOperator',['../classflex_gradient_operator.html',1,'flexGradientOperator&lt; T &gt;'],['../classflex_gradient_operator.html#aa83ae15b09ba2195951d8df803f08705',1,'flexGradientOperator::flexGradientOperator()']]],
  ['flexidentityoperator',['flexIdentityOperator',['../classflex_identity_operator.html',1,'flexIdentityOperator&lt; T &gt;'],['../classflex_identity_operator.html#acd55573556fc2313b0280f54c7a6730a',1,'flexIdentityOperator::flexIdentityOperator()']]],
  ['flexlinearoperator',['flexLinearOperator',['../classflex_linear_operator.html',1,'flexLinearOperator&lt; T &gt;'],['../classflex_linear_operator.html#ab4a525e1069965d018b8f4371db60234',1,'flexLinearOperator::flexLinearOperator()']]],
  ['flexmatrix',['flexMatrix',['../classflex_matrix.html',1,'flexMatrix&lt; T &gt;'],['../classflex_matrix.html#a435c0b9173f4b27ae6a81f3fbfebc428',1,'flexMatrix::flexMatrix()'],['../classflex_matrix.html#a47ca204d9c79473c830e7582a7ff4e87',1,'flexMatrix::flexMatrix(int aNumRows, int aNumCols, bool aMinus)']]],
  ['flexmatrixgpu',['flexMatrixGPU',['../classflex_matrix_g_p_u.html',1,'flexMatrixGPU&lt; T &gt;'],['../classflex_matrix_g_p_u.html#a8fb0c0049604ddd6c51d39e1e96781f6',1,'flexMatrixGPU::flexMatrixGPU()']]],
  ['flexmatrixlogical',['flexMatrixLogical',['../classflex_matrix_logical.html',1,'flexMatrixLogical&lt; T &gt;'],['../classflex_matrix_logical.html#a638c50a335498ef4f78d76f7304561f6',1,'flexMatrixLogical::flexMatrixLogical()'],['../classflex_matrix_logical.html#abbd2d5d1be94e9d98167e82b6f0395be',1,'flexMatrixLogical::flexMatrixLogical(int aNumRows, int aNumCols, bool aMinus)']]],
  ['flexprox',['flexProx',['../classflex_prox.html',1,'flexProx&lt; T &gt;'],['../classflex_prox.html#a6055dee6acc0a2eedebf11c6ee4b644b',1,'flexProx::flexProx()']]],
  ['flexproxdualboxconstraint',['flexProxDualBoxConstraint',['../classflex_prox_dual_box_constraint.html',1,'flexProxDualBoxConstraint&lt; T &gt;'],['../classflex_prox_dual_box_constraint.html#a2654a4ed37ad0eba9e6808f2a72ea1b3',1,'flexProxDualBoxConstraint::flexProxDualBoxConstraint()']]],
  ['flexproxdualdatahuber',['flexProxDualDataHuber',['../classflex_prox_dual_data_huber.html',1,'']]],
  ['flexproxdualdatakl',['flexProxDualDataKL',['../classflex_prox_dual_data_k_l.html',1,'']]],
  ['flexproxdualdatal1',['flexProxDualDataL1',['../classflex_prox_dual_data_l1.html',1,'']]],
  ['flexproxdualdatal2',['flexProxDualDataL2',['../classflex_prox_dual_data_l2.html',1,'']]],
  ['flexproxdualfrobenius',['flexProxDualFrobenius',['../classflex_prox_dual_frobenius.html',1,'']]],
  ['flexproxdualhuber',['flexProxDualHuber',['../classflex_prox_dual_huber.html',1,'flexProxDualHuber&lt; T &gt;'],['../classflex_prox_dual_huber.html#a4ab9fe05ffc64193bb7150cad6525610',1,'flexProxDualHuber::flexProxDualHuber()']]],
  ['flexproxdualinnerproduct',['flexProxDualInnerProduct',['../classflex_prox_dual_inner_product.html',1,'']]],
  ['flexproxduall1aniso',['flexProxDualL1Aniso',['../classflex_prox_dual_l1_aniso.html',1,'']]],
  ['flexproxduall1iso',['flexProxDualL1Iso',['../classflex_prox_dual_l1_iso.html',1,'']]],
  ['flexproxduall2',['flexProxDualL2',['../classflex_prox_dual_l2.html',1,'']]],
  ['flexproxduall2inf',['flexProxDualL2Inf',['../classflex_prox_dual_l2_inf.html',1,'']]],
  ['flexproxduallabeling',['flexProxDualLabeling',['../classflex_prox_dual_labeling.html',1,'']]],
  ['flexproxduallinf',['flexProxDualLInf',['../classflex_prox_dual_l_inf.html',1,'']]],
  ['flexsolver',['flexSolver',['../classflex_solver.html',1,'']]],
  ['flexsolverprimaldual',['flexSolverPrimalDual',['../classflex_solver_primal_dual.html',1,'']]],
  ['flexsolverprimaldualcuda',['flexSolverPrimalDualCuda',['../classflex_solver_primal_dual_cuda.html',1,'']]],
  ['flexsuperpixeloperator',['flexSuperpixelOperator',['../classflex_superpixel_operator.html',1,'flexSuperpixelOperator&lt; T &gt;'],['../classflex_superpixel_operator.html#a810ff259aed4c17eed5b6c731bb59b3b',1,'flexSuperpixelOperator::flexSuperpixelOperator()']]],
  ['flexterm',['flexTerm',['../classflex_term.html',1,'']]],
  ['flexzerooperator',['flexZeroOperator',['../classflex_zero_operator.html',1,'flexZeroOperator&lt; T &gt;'],['../classflex_zero_operator.html#a0d8f5246a460441e8ff71d6fe7359e23',1,'flexZeroOperator::flexZeroOperator()']]]
];
